from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyHttpUrl, BaseModel, Field


# Input type enum 
class InputType(str, Enum):
    TEXT = "text"
    URL = "url"

# Verdict enum
class Verdict(str, Enum):
    TRUE = "true"
    MISLEADING = "misleading"
    UNKNOWN = "unknown"

# Provider name enum
class ProviderName(str, Enum):
    GOOGLE = "google_factcheck"
    RAPID = "rapidapi_fact_checker"

# Provider result model
class ProviderResult(BaseModel):
    provider: ProviderName # Name of the provider
    verdict: Verdict # Verdict generated by the provider
    rating: Optional[str] = None # Rating generated by the provider
    title: Optional[str] = None # Title of the claim
    summary: Optional[str] = None # Summary of the claim
    source_url: Optional[AnyHttpUrl] = None # Source URL of the claim
    metadata: Dict[str, Any] = Field(default_factory=dict) # Metadata of the claim

# Aggregated result model
class AggregatedResult(BaseModel):
    claim_text: str # Text of the claim
    verdict: Verdict # Verdict generated by the providers
    votes: Dict[Verdict, int] # Votes for each verdict
    provider_results: List[ProviderResult] # Results from each provider
    providers_checked: List[ProviderName] = Field(default_factory=list) # Providers checked
    confidence: float = 0.0 # Confidence score
    explanation: Optional[str] = None  # Explanation generated by Gemini or other sources

# Text validate request model
class TextValidateRequest(BaseModel):
    text: str = Field(min_length=1)

# Url validate request model
class UrlValidateRequest(BaseModel):
    url: AnyHttpUrl

# Image validate request model
class ImageValidateRequest(BaseModel):
    image_base64: str = Field(description="Base64-encoded image content")

# Validate response model
class ValidateResponse(BaseModel):
    result: AggregatedResult


# Compatibility with existing routes expecting generic analyze endpoint
class AnalyzeRequest(BaseModel):
    text: Optional[str] = None
    url: Optional[AnyHttpUrl] = None
    image_base64: Optional[str] = None

# Analyze response model
class AnalyzeResponse(BaseModel):
    result: AggregatedResult

# Evidence model
class Evidence(BaseModel):
    snippet: str # Snippet of the evidence
    source: Optional[str] = None # Source of the evidence
    url: Optional[str] = None # URL of the evidence

# Provider rating model
class ProviderRating(BaseModel):
    provider: str # Name of the provider
    rating: Optional[str] = None # Rating of the provider
    label: Optional[str] = None  # "True" | "False" | "Unclear"

# Analyze response detailed model
class AnalyzeResponseDetailed(BaseModel):
    claim: str
    label: str  # "True" | "False" | "Unclear"
    rating: Optional[str] = None  # e.g., "Misleading", "Accurate", provider-style text rating
    confidence: float
    evidence: List[Evidence]
    providers: Optional[List[ProviderRating]] = None
    explanation: Optional[str] = None # Explanation generated by Gemini or other sources